echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_1_1.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_1_2.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_1_3.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_1_4.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_1_5.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_2_1.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_2_2.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_2_3.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_2_4.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_1_2_5.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_1_1.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_1_2.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_1_3.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_1_4.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_1_5.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_2_1.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_2_2.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_2_3.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_2_4.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_2_2_5.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_1_1.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_1_2.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_1_3.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_1_4.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_1_5.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_2_1.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_2_2.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_2_3.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_2_4.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort
echo '~/usr/r/R-3.1.2/bin/Rscript   /home/cocodong/class/hw4/veryShort/codeBreak_others_3_2_5.R' | qsub -e /home/cocodong/class/hw4/veryShort -o /home/cocodong/class/hw4/veryShort